/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMRC20 } from "./IMRC20";
export type { MRC20Token } from "./MRC20Token";
export type { Ownable } from "./Ownable";
